name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create-install-dir-test:
    name: create_install_dir.sh script test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Nested in current dir
        shell: bash
        env:
          INSTALL_DIR: '.sonar'
        run: |
          ./create_install_dir.sh > output
          grep -v "::error::" output
          test -d "${INSTALL_DIR}"

      - name: Nested in home
        shell: bash
        env:
          INSTALL_DIR: '~/.sonar'
        run: |
          ./create_install_dir.sh > output
          grep -v "::error::" output
          test -d "${INSTALL_DIR}"

      - name: Empty install dir specified
        shell: bash
        env:
          INSTALL_DIR: ''
        run: |
          (./create_install_dir.sh || echo "=== Script failed ===") > output
          grep "::error::Empty installation-dir specified" output
          grep "=== Script failed ===" output

      - name: No permission to create directory
        shell: bash
        env:
          INSTALL_DIR: '/non_creatable'
        run: |
          (./create_install_dir.sh || echo "=== Script failed ===") > output
          grep "::error::Failed to create non-existing installation-dir '/non_creatable'" output
          grep "=== Script failed ===" output

      - name: Existing but not directory
        shell: bash
        env:
          INSTALL_DIR: 'not_directory'
        run: |
          echo "- Create normal file"
          echo "content" > "${INSTALL_DIR}"

          echo "- Test script behavior"
          (./create_install_dir.sh || echo "=== Script failed ===") > output
          grep "::error::Installation-dir 'not_directory' is not a directory" output
          grep "=== Script failed ===" output


      - name: Existing but not readable
        shell: bash
        env:
          INSTALL_DIR: 'not_readable'
        run: |
          echo "- Create dir and make it not readable"
          mkdir -p "${INSTALL_DIR}"
          chmod -r "${INSTALL_DIR}"

          echo "- Test script behavior"
          (./create_install_dir.sh || echo "=== Script failed ===") > output
          grep "::error::Installation-dir 'not_readable' is not readable" output
          grep "=== Script failed ===" output

      - name: Existing but not writeable
        shell: bash
        env:
          INSTALL_DIR: 'not_writeable'
        run: |
          echo "- Create dir and make it not writeable"
          mkdir -p "${INSTALL_DIR}"
          chmod -w "${INSTALL_DIR}"

          echo "- Test script behavior"
          (./create_install_dir.sh || echo "=== Script failed ===") > output
          grep "::error::Installation-dir 'not_writeable' is not writeable" output
          grep "=== Script failed ===" output

  setup-script-test:
    name: setup.sh script test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Windows
        shell: bash
        env:
          OS: 'Windows'
          INSTALL_DIR: 'install-directory'
          SONAR_HOST_URL: 'http://sonar-host.com'
          SONAR_SCANNER_VERSION: 'vX.Y.Z.MMMM'
        run: |
          ./setup.sh > output
          grep -v "::error::" output

          echo "- Check sonar-scanner:"
          grep "sonar-scanner-url=https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-vX.Y.Z.MMMM-windows.zip" output
          grep "sonar-scanner-dir=install-directory/sonar-scanner-vX.Y.Z.MMMM-windows" output
          grep "sonar-scanner-bin=install-directory/sonar-scanner-vX.Y.Z.MMMM-windows/bin/sonar-scanner.bat" output

          echo "- Check build-wrapper:"
          grep "build-wrapper-url=http://sonar-host.com/static/cpp/build-wrapper-win-x86.zip" output
          grep "build-wrapper-dir=install-directory/build-wrapper-win-x86" output
          grep "build-wrapper-bin=install-directory/build-wrapper-win-x86/build-wrapper-win-x86-64.exe" output

      - name: Linux
        shell: bash
        env:
          OS: 'Linux'
          INSTALL_DIR: 'install-directory'
          SONAR_HOST_URL: 'http://sonar-host.com'
          SONAR_SCANNER_VERSION: 'vX.Y.Z.MMMM'
        run: |
          ./setup.sh > output
          grep -v "::error::" output

          echo "- Check sonar-scanner:"
          grep "sonar-scanner-url=https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-vX.Y.Z.MMMM-linux.zip" output
          grep "sonar-scanner-dir=install-directory/sonar-scanner-vX.Y.Z.MMMM-linux" output
          grep "sonar-scanner-bin=install-directory/sonar-scanner-vX.Y.Z.MMMM-linux/bin/sonar-scanner" output

          echo "- Check build-wrapper:"
          grep "build-wrapper-url=http://sonar-host.com/static/cpp/build-wrapper-linux-x86.zip" output
          grep "build-wrapper-dir=install-directory/build-wrapper-linux-x86" output
          grep "build-wrapper-bin=install-directory/build-wrapper-linux-x86/build-wrapper-linux-x86-64" output

      - name: macOSX
        shell: bash
        env:
          OS: 'macOS'
          INSTALL_DIR: 'install-directory'
          SONAR_HOST_URL: 'http://sonar-host.com'
          SONAR_SCANNER_VERSION: 'vX.Y.Z.MMMM'
        run: |
          ./setup.sh > output
          grep -v "::error::" output

          echo "- Check sonar-scanner:"
          grep "sonar-scanner-url=https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-vX.Y.Z.MMMM-macosx.zip" output
          grep "sonar-scanner-dir=install-directory/sonar-scanner-vX.Y.Z.MMMM-macosx" output
          grep "sonar-scanner-bin=install-directory/sonar-scanner-vX.Y.Z.MMMM-macosx/bin/sonar-scanner" output

          echo "- Check build-wrapper:"
          grep "build-wrapper-url=http://sonar-host.com/static/cpp/build-wrapper-macosx-x86.zip" output
          grep "build-wrapper-dir=install-directory/build-wrapper-macosx-x86" output
          grep "build-wrapper-bin=install-directory/build-wrapper-macosx-x86/build-wrapper-macosx-x86" output

      - name: Unssuported OS
        shell: bash
        env:
          OS: 'unsupportedOS'
          INSTALL_DIR: 'install-directory'
          SONAR_HOST_URL: 'http://sonar-host.com'
          SONAR_SCANNER_VERSION: 'vX.Y.Z.MMMM'
        run: |
          (./setup.sh  || echo "=== Script failed ===") > output

          echo "- Check errors:"
          grep "::error::Unsupported runner OS 'unsupportedOS'" output
          grep "=== Script failed ===" output

  download-script-test:
    name: download.sh script test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Download test without validation
        shell: bash
        env:
          INSTALL_DIR: 'install-directory'
          DOWNLOAD_URL: 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip'
          SHA_DOWNLOAD_URL: 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip.sha256'
          TMP_ZIP_PATH: ${{ runner.temp }}/sonar-scanner.zip
        run: |
          ./download.sh > output
          test -f "$TMP_ZIP_PATH"
          if [ -f "$TMP_ZIP_PATH.sha256" ]; then
            echo "$TMP_ZIP_PATH.sha256 shouldn't exist"
            exit 1
          fi
          grep -v "::error::" output
      - name: Download test with validation
        shell: bash
        env:
          INSTALL_DIR: 'install-directory-sha-validation'
          DOWNLOAD_URL: 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip'
          SHA_DOWNLOAD_URL: 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip.sha256'
          TMP_ZIP_PATH: ${{ runner.temp }}/sonar-scanner.zip
        run: |
          ./download.sh -v > output
          test -f "$TMP_ZIP_PATH"
          test -f "$TMP_ZIP_PATH".sha256
          grep -v "::error::" output
      - name: Incorrect install dir
        shell: bash
        env:
          INSTALL_DIR: ''
        run: |
          (./download.sh || echo "=== Script failed ===") > output
          grep "::error::Failed to create" output
          grep "=== Script failed ===" output
      - name: Incorrect download url
        shell: bash
        env:
          INSTALL_DIR: 'install-directory'
          DOWNLOAD_URL: 'incorrect-url'
        run: |
          (./download.sh || echo "=== Script failed ===") > output
          grep "::error::Failed to download 'incorrect-url'" output
          grep "=== Script failed ===" output
      - name: Incorrect SHA256 url
        shell: bash
        env:
          INSTALL_DIR: 'install-directory'
          DOWNLOAD_URL: 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip'
          SHA_DOWNLOAD_URL: incorrect-sha256-url
          TMP_ZIP_PATH: ${{ runner.temp }}/sonar-scanner.zip
        run: |
          (./download.sh -v || echo "=== Script failed ===") > output
          grep "::error::Failed to download 'incorrect-sha256-url'" output
          grep "=== Script failed ===" output

  output-test:
    name: Action outputs
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        cache: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install sonar-scanner
        id: install-sonar-scanner
        uses: ./
        with:
          cache-binaries: ${{ matrix.cache }}

      - name: SONAR_HOST_URL is set
        shell: bash
        run: |
          [[ $SONAR_HOST_URL == "https://sonarcloud.io" ]]

      - name: sonar-scanner is installed and in PATH
        run: |
          sonar-scanner --help | grep "INFO: usage: sonar-scanner "

      - name: sonar-scanner-binary output is correct
        shell: bash
        env:
          BINARY: ${{ steps.install-sonar-scanner.outputs.sonar-scanner-binary }}
        run: |
          "$BINARY" --help | grep "INFO: usage: sonar-scanner "

      # build-wrapper does not have --help or equivalent option.
      # Pass to few arguments and ignore error code
      - name: build-wrapper is installed and in PATH on Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          (build-wrapper-win-x86-64.exe || true) | grep "build-wrapper, version "

      - name: build-wrapper is installed and in PATH on Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          (build-wrapper-linux-x86-64 || true) | grep "build-wrapper, version "

      - name: build-wrapper is installed and in PATH on macOS
        if: runner.os == 'macOs'
        shell: bash
        run: |
          (build-wrapper-macosx-x86 || true) | grep "build-wrapper, version "

      - name: build-wrapper-binary output is correct
        shell: bash
        env:
          BINARY: ${{ steps.install-sonar-scanner.outputs.build-wrapper-binary }}
        run: |
          ("$BINARY" || true) | grep "build-wrapper, version "
